### PR TITLE
Fix Issue MTS960 API change

### PR DESCRIPTION
**Pull request by bernardpe**
Hi,

I was facing to somes issue using MTS960, is seems that interface has been changed since.
I made the evolution to make the solution working.

Regards,
Bernard

### CODE REVIEW

**Comment by bernardpe** [comment]
related to [Issue on Managing MTS960 due to API change](https://github.com/krahabb/meross_lan/issues/449#top)
#449

**Comment by krahabb** [comment]
Hello @bernardpe,
Thank you for the PR. I've just better checked the diff and everything looks ok. I'd just want to slightly refactor the `_mts_working` moving it to the inherited (MTS960) thermostat class instead of the base `MTSClimate` since it's really a custom feature not present in any other MTSClimate derived class.
I'd fix that directly in your branch but I'm in a rush at the moment (and I guess I can't directly touch it without going with a fork-PR on your repo). If you can manage it I would be grateful else I guess I could just merge this and then apply the edit on my repo. I think I'll manage it over-night or so in order to promptly merge this.

**Comment by bernardpe** [comment]
Hi

No problem I will do the work for tomorrow !


Bernard

**Comment by bernardpe** [comment]
Hi,
change has been made and I fix the issue of the test as well.
Bernard

**Pull request merged**
